// Generated by https://quicktype.io

export interface CountryModel {
    data: Datum[];
    _cacheHit: boolean;
}

export interface Datum {
    coordinates: Coordinates;
    name: string;
    code: string;
    population: number | null;
    updated_at: string;
    today: Today;
    latest_data: LatestData;
}

export interface Coordinates {
    latitude: number | null;
    longitude: number | null;
}

export interface LatestData {
    deaths: number;
    confirmed: number;
    recovered: number;
    critical: number;
    calculated: Calculated;
}

export interface Calculated {
    death_rate: number | null;
    recovery_rate: number | null;
    recovered_vs_death_ratio: null;
    cases_per_million_population: number;
}

export interface Today {
    deaths: number;
    confirmed: number;
}
