// Generated by https://quicktype.io

export interface WorldModel {
    totalCases: string;
    recovered: string;
    deaths: string;
    activeCases: string;
    closedCases: string;
    lastUpdate: string;
}
